config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home' , to: 'pages#home'
  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup',to:'chefs#new'
  resources :chefs,except:[:new]

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'
  resources :ingredients
  # get '/recipes', to: 'recipes#index'
  # get "/recipes/new", to: 'recipes#new' , as: 'new_recipe'
  # get "/recipes/:id", to: 'recipes#show', as: 'recipe'
  # post "/recipes", to:'recipes#create'
  get "/chat" , to: 'chatrooms#show'
  mount ActionCable.server => '/cable'
  resources :messages ,only: [:create]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
 validates :name ,presence:true
 validates :description ,presence:true ,length:{minimum:5 ,maximum:500}
 belongs_to :chef
 validates :chef_id, presence: true
 default_scope -> {order(updated_at: :desc)} 
 has_many :recipe_ingredients
 has_many :ingredients, through: :recipe_ingredients
 has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only:[:show,:update,:edit,:destroy]
    before_action :require_user, except:[:index,:show]
    before_action :require_same_user, only:[:edit,:destroy,:update]

    def index
        @recipes = Recipe.paginate(page:params[:page],per_page:5)
    end

    def show
        @comment = Comment.new
        @comments = @recipe.comments.paginate(page: params[:page],per_page: 5)
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = current_chef
        if @recipe.save
            flash[:success] = "Recipe was created successfully!"
            redirect_to recipe_url(@recipe)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @recipe.update(recipe_params)
            flash[:notice] = 'Recipe updated successfully'
            redirect_to recipe_url(@recipe)
        else
            render 'edit'
        end
    end

    def destroy
        @recipe.destroy
        flash[:notice] = 'Recipe deleted successfully'
        redirect_to recipes_path
    end

    private
        def set_recipe
            @recipe = Recipe.find(params[:id])
        end

        def recipe_params
            params.require(:recipe).permit(:name,:description, ingredient_ids: [] )
        end

        def require_same_user
            if current_chef != @recipe.chef and !current_chef.admin?
                flash[:danger] = "Not your recipe"
                redirect_to recipes_path
            end
        end
end

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
        <%= gravatar_for(recipe.chef) %>
      </section>
    </div>
    <div class="col-md-8 bg-light border px-3 py-1 my-1 ">
      <h4><%= link_to recipe.name,recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      
      <% if recipe.ingredients.any? %>
        <p> Ingredients: <%= render recipe.ingredients %> </p>
      <% end %>
      
      <p>
        <span class="quiet"><small>Created 
        <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.name.capitalize %> </small></span>
      </p> 
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
         <%= link_to 'Edit recipe', edit_recipe_path(recipe) ,class: 'btn btn-sm btn-warning' %>
         <%= link_to 'Delete recipe', recipe_path(recipe), method: :delete, data:{confirm:'Are you sure?'},class:'btn btn-sm btn-danger' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1 align='center' >Edit recipes</h1>
<hr />

<% if @recipe.errors.any? %>
    <%= pluralize(@recipe.errors.count,'error') %>
    prohibited this <%= @recipe.class %>'s creation
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
        <li > <%= msg %> </li>
    <% end %>
    </ul>
<% end %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="mb-3">
        <div class="form-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", 
                                placeholder: "Name of recipe",
                                autofocus: true %>
        </div>
      </div>
      <div class="mb-3">
        <div class="form-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description,
                    rows: 10, 
                    class: "form-control", 
                    placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
            <% cb.label(class: 'checkbox-inline mx-1 input_checkbox') {cb.check_box(class: 'checkbox mx-1') + cb.text} %>
        <% end %>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-12 col-md-offset-4 center">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<h1 align='center' >Listing all Recipes</h1>
<hr />

<div align='center' class='paginate'>
  <%= will_paginate %>
</div>
<div align='center'>
  <%= render 'recipe', obj: @recipes %>
</div>

app/views/recipes/new.html.erb
<h1 align='center' >Create a new recipes</h1>
<hr />

<%= render 'shared/errors' , obj: @recipe %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="mb-3">
        <div class="form-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", 
                                placeholder: "Name of recipe",
                                autofocus: true %>
        </div>
      </div>
      <div class="mb-3">
        <div class="form-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description,
                    rows: 10, 
                    class: "form-control", 
                    placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="mb-3">
        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
            <% cb.label(class: 'checkbox-inline mx-1 input_checkbox') {cb.check_box(class: 'checkbox mx-1') + cb.text} %>
        <% end %>
   </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-12 col-md-offset-4 center">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<h2 align='center' >Recipe Name: <%= @recipe.name.capitalize %> </h2>
<hr/>
<div class='p-3 bg-light'>
    <h4 class='center description'> <strong> Steps: </strong> </h4>
    <hr/>
    <%= simple_format(@recipe.description) %>
    <hr />
    
    <% if @recipe.ingredients.any? %>
      <p> Ingredients: <%= render @recipe.ingredients %> </p>
    <% end %>
    
  <div class="pull-right">
    <p>
      Created by:
    </p>
    <p>
        <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
    </p>
    <p>
      <p> <small><%= @recipe.chef.name.capitalize %></small> </p> 
       <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?)  %>
        <%= link_to 'Edit recipe',edit_recipe_path(@recipe) ,class: 'btn btn-sm btn-warning' %>
        <%= link_to 'Delete recipe', recipe_path(@recipe), method: :delete, data:{confirm:'Are you sure?'},class:'btn btn-sm btn-danger' %>
      <% end %>
        <%= link_to "Return to all recipe's", recipes_path , class:'btn btn-sm btn-primary' %>
      <div align='right'>
        <%= time_ago_in_words(@recipe.created_at) %> ago
      </div>
    </p>
  </div>
</div>

<% if logged_in? %>
    <div class='row'>
      <div class='col-md-8 offset-md-2'>
        <h3>Comments:</h3>
        <hr/>
        <%= form_for([@recipe,@comment],remote: true, :html =>{class: 'form-horizontal',role:'form'}) do |f| %>
          <div class='mb-3 row'>
        <div class="form-label col-md-2">
          <%= f.label :description, "Comment:  "  %>
        </div>
        <div class="col-md-10">
          <%= f.text_area :description,
                    rows: 5, 
                    class: "form-control", 
                    placeholder: "Enter your comment" %>
        </div>
      </div>
      <%= f.submit "Submit comment", class: "btn btn-primary offset-md-2" %>
        <% end %>
      </div>
    </div>
<% end %>

<% if @recipe.comments.count != 0 %>
  <div class='row my-4'>
    <div class='col-md-8 offset-md-2'> 
      <h3>Prior Comments:</h3>
      <div id="comments">
        <div id="messages" >
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
      </div>
    </?>
  </div>
<% else %>
  <div class='row my-4'>
    <div class='col-md-8 offset-md-2'>
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>