config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home' , to: 'pages#home'
  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup',to:'chefs#new'
  resources :chefs,except:[:new]

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'
  resources :ingredients
  # get '/recipes', to: 'recipes#index'
  # get "/recipes/new", to: 'recipes#new' , as: 'new_recipe'
  # get "/recipes/:id", to: 'recipes#show', as: 'recipe'
  # post "/recipes", to:'recipes#create'
  get "/chat" , to: 'chatrooms#show'
  mount ActionCable.server => '/cable'
  resources :messages ,only: [:create]

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence:true
    validates_uniqueness_of :name 
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients 
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    
    before_action :set_ingredient , only: [:edit, :update, :show]
    before_action :require_admin , except: [:show, :index]
    def new
        @ingredient = Ingredient.new 
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
            flash[:success] = 'Ingredient created successfully'
            redirect_to ingredient_path(@ingredient)
        else
            render 'new'
        end
    end

    def edit
         
    end

    def update
        if @ingredient.update(ingredient_params)
            flash[:success] = 'Ingredient updated successfully'
            redirect_to ingredient_path(@ingredient)
         else
             render 'edit'
         end
    end

    def show
        @ingredient_recipe = @ingredient.recipes.paginate(page:params[:page],per_page: 5)
    end

    def index
        @ingredients = Ingredient.paginate(page:params[:page],per_page: 5)
    end

    private

        def ingredient_params
            params.require(:ingredient).permit(:name)
        end

        def require_admin
            if !logged_in? || ( logged_in? && !current_chef.admin?)
                flash[:danger] = 'Admin access required'
                redirect_to ingredients_path
            end
        end

        def set_ingredient
            @ingredient = Ingredient.find(params[:id])
        end

end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient, :html => {class: 'form-horizontal',role: 'form'}) do |f| %>
  <div class="mb-3">
    <%= f.label :name , class: "form-label", placeholder: 'Enter Ingredient' %>
    <%= f.text_field :name,class: 'form-control' %>
   </div>
  <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient" , class: "btn btn-primary") %>
<% end %>

app/views/ingredients/_ingredient.html.erb
<span class='badge bg-info'>
    <%= link_to ingredient.name, ingredient_path(ingredient) %> &nbsp; </span>

app/views/ingredients/edit.html.erb
<h1 align='center' >Edit ingredient name</h1>
<hr />

<%= render "form"  %>

app/views/ingredients/index.html.erb
<h1 align='center'>Available Ingredients</h1>
<hr/>

<div align='center'>
    <div class='paginate'>
        <%= will_paginate %>
    </div>
    <% @ingredients.each do |ing| %>
        <ul class='listing'>
            <div class='row'>
                <div class='bg-light items offset-md-4 col-md-4'>
                    <li class='chef-title'> <%= link_to ing.name.capitalize, ingredient_path(ing) %> </li>
                    <li> <small> <%= pluralize(ing.recipes.count, "recipe") if ing.recipes %> </small> </li>
                    <% if logged_in? && current_chef.admin?  %>
                        <li > <%= link_to 'Edit this Ingredient', edit_ingredient_path(ing), class:'btn btn-sm btn-warning' %> </li>
                    <% end %>
                </div>
            </div>
        </ul>
    <% end %>
</div>

app/views/ingredients/new.html.erb
<h1 align="center">Add new Ingredient</h1>
<hr/>

<%= render "form"  %>

app/views/ingredients/show.html.erb
<h1 align='center' > <%= @ingredient.name %> </h1>
<hr />


<hr/>
<% if @ingredient.recipes.count > 0 %>
    <h4 align='center' > Recipes containing <%= @ingredient.name %> </h4>
    <div class='paginate'>
            <%= will_paginate @ingredient_recipe %>
    </div>
    <%= render 'recipes/recipe', obj: @ingredient_recipe %>
<% else %>
    <h4 align='center'>No recipes yet!</h4>
<% end %>