config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home' , to: 'pages#home'
  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup',to:'chefs#new'
  resources :chefs,except:[:new]

  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'
  resources :ingredients
  # get '/recipes', to: 'recipes#index'
  # get "/recipes/new", to: 'recipes#new' , as: 'new_recipe'
  # get "/recipes/:id", to: 'recipes#show', as: 'recipe'
  # post "/recipes", to:'recipes#create'
  get "/chat" , to: 'chatrooms#show'
  mount ActionCable.server => '/cable'
  resources :messages ,only: [:create]

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "MyRecipes", root_path, class: 'navbar-brand', id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          <%= link_to 'ChefChat', chat_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to "Chefs", chefs_path, class: 'nav-link' %>
        </li>
       <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ingredient
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <%# <li><a class="dropdown-item" href="#">Action</a></li> %>
            <li><%= link_to 'All Ingredients', ingredients_path , class: 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
              <% Ingredient.all.each do |ing| %>
                 <li><%= link_to ing.name.capitalize, ingredient_path(ing) , class: 'dropdown-item' %></li>
              <% end %>        
              <% if logged_in? && current_chef.admin? %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to 'Create new Ingredients', new_ingredient_path , class: 'dropdown-item' %></li>    
              <% end %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Recipes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li> <%= link_to 'All recipes', recipes_path,class: 'dropdown-item' %> </li>
            <li> <%= link_to 'Create new recipes', new_recipe_path,class: 'dropdown-item' %> </li>
          </ul>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a> %>
        </li>
      </ul>
      <form class="d-flex m-auto">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
           <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_chef.name.capitalize %>'s Profile <%= "Admin" if current_chef.admin? %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

              <li><%= link_to "View your profile", 
                                chef_path(current_chef) ,class: 'dropdown-item' %></li>
              <li><%= link_to "Edit your profile", 
                                edit_chef_path(current_chef) ,class: 'dropdown-item' %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, 
                                      method: :delete, class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path , class: 'nav-link' %></li>  
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>  

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navigation" %>
      <div class='container'>
        <div class="row">
          <div class="col-md-12">
            <% flash.each do |name, msg| %>
              <div class="alert alert-<%= name %>">
                <%= msg %>
                <a href="#" class="close" data-dismiss="alert">×</a>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>